version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - sam build
  post_build:
    commands:
      - echo Build completed, beginning deployment
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset